makentu15:
  datasource:
      driver-class-name: ${your_database}
      host: ${your_host}
      port: ${your_port}
      database: ${your_databases_name}
      username: ${your_user_name}
      password: ${your_password}
#    host: localhost
#    port: 6379
#    database: 0
#google:
#  api-key: AIzaSyDxdXdO7o2eWLclcT9tI8UAtdEa7cN5wd4
